### ISSUE TITLE
Missing copyright notice as required by Mozilla Public License 2.0

### ISSUE THREAD

**Issue by robcowart** [hashicorp/go-uuid#15]
The Mozilla Public License 2.0 license requires a copyright notice, see below...

![image](https://user-images.githubusercontent.com/10326954/160115105-2bd6f07a-25a0-42ad-98dd-b2f290270084.png)

Can you please add a NOTICE file with a copyright notice for this code, or place the copyright notice at the top of the LICENSE file. It is causing legal review problems for applications that use this module.

Any assistance here would be appreciated.

**Comment by jefferai** [comment]
Hi there,

Thanks for submitting this! I'm going to add a copyright notice to the license file now, and will tag a new version.

More broadly, this issue has kicked off internal discussion about _all_ of our repos and the fact that we may be non-compliant across many of them. We have a whole lot of them so addressing them (ideally automatically) is going to take us a while but it's now on the radar of our legal and internal infrastructure teams, so thanks for pointing this out, as it's important that we are in compliance with the license terms!

**Comment by robcowart** [comment]
Thanks for this. If it helps your legal team to prioritize, the Apache 2.0 license is another that requires a copyright which many repos do not have.
