### ISSUE TITLE
Potential for non-random UUID generation

### ISSUE THREAD

**Issue by gaffneyc** [hashicorp/go-uuid#8]
Looking through the code today and saw that [GenerateRandomBytes](https://github.com/hashicorp/go-uuid/blob/de160f5c59f693fed329e73e291bb751fe4ea4dc/uuid.go#L10) was not validating how many bytes were read from the random source. There was a similar issue in [satori/go.uuid](https://github.com/satori/go.uuid/issues/73) where people were seeing trailing 0s. The quick fix was to use [io.ReadFull](https://github.com/satori/go.uuid/pull/75/files).

**Comment by jefferai** [comment]
rand.Read actually does this for you. See https://golang.org/pkg/crypto/rand/#Read
